import type { Manifest } from "../types.js";

export function generateReadme(manifest: Manifest): string {
  const lines: string[] = [
    "# dotai config",
    "",
    "AI CLI configurations managed by [dotai](https://github.com/dotai/dotai).",
    "",
    "## Quick Start",
    "",
    "```bash",
    "npx dotai use <this-repo>",
    "```",
    "",
    "## Managed Tools",
    "",
  ];
  for (const [name, tool] of Object.entries(manifest.tools)) {
    lines.push(`### ${name}`);
    lines.push(`- Source: \`${tool.source}\``);
    lines.push(`- Includes: ${tool.include.map((i) => `\`${i}\``).join(", ")}`);
    lines.push("");
  }
  lines.push("---");
  lines.push("*Auto-generated by `dotai export`. Do not edit manually.*");
  lines.push("");
  return lines.join("\n");
}
